// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bftehfkjevtofacaiwxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdGVoZmtqZXZ0b2ZhY2Fpd3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTAwOTksImV4cCI6MjA3NDcyNjA5OX0.l0dFAnxx04ovJI2BOtYO7S94X5NKev7Setyoct_ascU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});